### ISSUE TITLE
Redirects not working unless Forced Redirect checked in 7.1.8

### ISSUE THREAD

**Issue by akeilox** [kipusoep/UrlTracker#106]
I saw the discussion on 7.3 multiple domains, but Im having this issue where I upgraded from 2.x to latest 3.9 of on a 7.1.8 umbraco installation. On 2.x it was working fine without requiring 

Its capturing the page rename/moves but the redirect is not working unless i click Advanced and change to Force Redirect.

Editors will not be able to do that, so my question is should i go back to a previous version of Url Tracker or is there any way to set Force Redirect checkbox to be checked automatically for newly created entries?

Another point is I clicked clear 404 not found list, in hope that I will have a clean 404 list to work after upgrade. However the 404 not found button is not showing even though I hit 404 pages for the past two days. The 404 section/button simply doesnt show up.

Would appreciate any feedback.

**Comment by akeilox** [comment]
Quick update, for pre 7.3 (tested on 7.1.8):

if i download the 3.9 sources and change those lines back ;
<pre>
-            context.PostRequestHandlerExecute += context_PostRequestHandlerExecute;
+            context.EndRequest += context_EndRequest;
</pre>

and
<pre>
-        void context_PostRequestHandlerExecute(object sender, EventArgs e)
+        void context_EndRequest(object sender, EventArgs e)

</pre>

the redirects are working without requiring to check Force Redirect.

Without further insight, i suspect the 3.9 update of 301 tracker is breaking existing redirect functionality for pre 7.3 (again, only tested on 7.1.8, for now).

Not sure what else is changed but my previous redirect entries like 

<pre>/oldpage.asp  to /new-page-url  </pre>


are not working anymore in 3.9, even with the above changes being reversed. Not sure if there is anything else related.

Would be interested to hear your thoughts on this.

**Comment by kipusoep** [comment]
That's really weird, because 3.9 was released with ```context.EndRequest```, not ```context.PostRequestHandlerExecute```.
That's just a change I got via a PR, but is still being tested (doesn't work for me).

**Comment by akeilox** [comment]
my bad, i did install 3.9 then to be sure i downloaded the source from github and compiled. I didnt notice 3.9 vs source was different.
When i came across the post, checked the source to notice it was changed and revert it back to context.EndRequest.

That returned to normal in umbraco 7.1.8. 
However the /oldpage.asp to /new-page-url (i.e. the extension based rules) stopped working (compared to 2.x).

**Comment by kipusoep** [comment]
I think the only way for me to really look into this, is if I have the project incl. database so I can attach the source and see what happens in the Url Tracker code.

**Comment by kipusoep** [comment]
Could you also try with [3.10-rc](https://www.nuget.org/packages/UrlTracker/3.10.0-rc)?

**Comment by kipusoep** [comment]
This should be fixed with v3.9 and Umbraco 7.3.2.
