### ISSUE TITLE
Redirect to picked content node causes Null reference exception

### ISSUE THREAD

**Issue by cpevans** [kipusoep/UrlTracker#107]
In Umbraco v7.3.0  Installed the UrlTracker package. The dashboard and creating of rules seems to work fine (including automatic rules being created from renaming pages etc).

However, on the front-end of the website when visiting an old URL that triggers a redirect to a picked content node, get the following error:

[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +275
   Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +47
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +79
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +115
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +265
   InfoCaster.Umbraco.UrlTracker.Helpers.UmbracoHelper.GetUrl(Int32 nodeId) in d:\kipusoep\Documents\GitHub\UrlTracker\Helpers\UmbracoHelper.cs:139
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.LoadUrlTrackerMatchesFromDatabase(HttpRequest request, String urlWithoutQueryString, Boolean urlHasQueryString, String shortestUrl, Int32 rootNodeId, String& redirectUrl, Nullable`1& redirectHttpCode, Boolean& redirectPassThroughQueryString) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:412
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:199
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_EndRequest(Object sender, EventArgs e) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:81
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91

This happens when using version 3.9.1 from Nuget, as well as the 3.9 download from https://our.umbraco.org/projects/developer-tools/301-url-tracker

Note that manual redirects created mapping an old URL to a new URL manually (ie. typing in an actual destination URL rather than picking an Umbraco content node) works fine.

**Comment by kipusoep** [comment]
There's a search feature on Github, you know? :-)
https://github.com/kipusoep/UrlTracker/issues/90

**Comment by cpevans** [comment]
Thanks Stefan, I didn't look at closed issues which is probably how I missed that one. Although I notice that the OP has just posted again saying that U7.3.2 and v3.9 still throws the error?

**Comment by kipusoep** [comment]
That's possible, don't have any spare time at the moment to look at it.
