### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by mcgawn** [kipusoep/UrlTracker#109]
Can this be used for that redirect but matching all urls? as i cant find out how to do it if it can be done through the app, but apart from that big thumbs up for the app, working on 7.3 with only one small issue of having to check force redirect checkbox for every redirect to work :-)

**Comment by kipusoep** [comment]
Nope, but here's a IIS rewrite rule to do it:

```lang=xml
<rule name="Force HTTPS" stopProcessing="true" enabled="false">
  <match url=".*" />
  <conditions>
	<add input="{HTTPS}" pattern="off" />
  </conditions>
  <action type="Redirect" url="https://{HTTP_HOST}/{R:0}" />
</rule>

**Comment by mcgawn** [comment]
Yeah cheers know how to do it that way just seeing if the app could do it :-)
