### ISSUE TITLE
'IX_icUrlTracker' already exists on table 'icUrlTracker'

### ISSUE THREAD

**Issue by shearer3000** [kipusoep/UrlTracker#110]
I get this start up issue on Url Tracker v3.9:

The EXECUTE permission was denied on the object 'sp_helpindex', database 'mssqlsystemresource', schema 'sys'.
The operation failed because an index or statistics with name 'IX_icUrlTracker' already exists on table 'icUrlTracker'.

The user the site runs under is a member of the db_owner role, it looks like the Url Tracker startup code is trying to recreate an index that is already there?

**Comment by kipusoep** [comment]
Never seen this error before, so it sounds to me like it's an environment specific issue. Something to do with permissions I guess? Maybe it's even unable to read if the index already exists?

**Comment by daniel-chenery** [comment]
I'm going to close this for inactivity. Do comment back if the error happens again though.
