### ISSUE TITLE
DOesn't work in 7.2 or 7.3

### ISSUE THREAD

**Issue by jonathanS8080** [kipusoep/UrlTracker#111]
Hi,
When I create a new Url Tracker:
Old URL = /test
Redirect node = /somewhereelse
Redirect type = Permanent 301
(everything else left empty)
I get a 404 error.
Does this work for these versions? I see on the our Umbraco site 7.3 has 29% tested but does this mean it doesnt work?
Thanks
Jon

**Comment by kipusoep** [comment]
From the readme:

Umbraco 7.3.x

Umbraco 7.3.x has known issues with the Url Tracker. These are resolved in Umbraco 7.4, so please don't use 7.3.x in combination with the Url Tracker.
