### ISSUE TITLE
Log4Net Assembly issue during install

### ISSUE THREAD

**Issue by ryanmcdonough** [kipusoep/UrlTracker#112]
When attempting to install the package via the Packages interfact on Umbraco 4.7.1 I get

Server Error in '/' Application.

Could not load file or assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=null' could not be loaded.

=== Pre-bind state information ===
LOG: DisplayName = log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/dev/website-website/website.WebApp/
LOG: Initial PrivatePath = C:\dev\website-website\website.WebApp\bin
Calling assembly : InfoCaster.Umbraco.UrlTracker, Version=3.10.5847.28108, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\dev\website-website\website.WebApp\web.config
LOG: Using host configuration file: C:\Users\ryan.mcdonough\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/ryan.mcdonough/AppData/Local/Temp/Temporary ASP.NET Files/root/9451e87b/742131e2/log4net.DLL.
LOG: Attempting download of new URL file:///C:/Users/ryan.mcdonough/AppData/Local/Temp/Temporary ASP.NET Files/root/9451e87b/742131e2/log4net/log4net.DLL.
LOG: Attempting download of new URL file:///C:/dev/website-website/website.WebApp/bin/log4net.DLL.
LOG: Attempting download of new URL file:///C:/dev/website-website/website.WebApp/bin/log4net/log4net.DLL.
LOG: Attempting download of new URL file:///C:/Users/ryan.mcdonough/AppData/Local/Temp/Temporary ASP.NET Files/root/9451e87b/742131e2/log4net.EXE.
LOG: Attempting download of new URL file:///C:/Users/ryan.mcdonough/AppData/Local/Temp/Temporary ASP.NET Files/root/9451e87b/742131e2/log4net/log4net.EXE.
LOG: Attempting download of new URL file:///C:/dev/website-website/website.WebApp/bin/log4net.EXE.
LOG: Attempting download of new URL file:///C:/dev/website-website/website.WebApp/bin/log4net/log4net.EXE.

**Comment by kipusoep** [comment]
What version are you installing? Umbraco v4 isn't supported anymore.

**Comment by ryanmcdonough** [comment]
The version from the Umbraco package installer, does the Umbraco packager installer not serve the version that the version of Umbraco in use can deal with?

**Comment by kipusoep** [comment]
No it doesn't AFAIK. Anyway, you can try UrlTracker v2: https://our.umbraco.org/FileDownload?id=12095
But can't promise you it'll work, Umbraco 4.7 is really old now.

**Comment by ryanmcdonough** [comment]
@kipusoep thanks - and don't I know it, ancient isn't enough of a description for this site.

**Comment by kipusoep** [comment]
No problem and good luck!
