### ISSUE TITLE
Delete all automatic entries?

### ISSUE THREAD

**Issue by UmbracoNewb** [kipusoep/UrlTracker#113]
Hi

We have an issue where we need to delete all automatic entries from the database. I can't seem to identify how you find/select the automatic entries in the database though?

/Dennis

**Comment by kipusoep** [comment]
```c#
RedirectNodeId.HasValue && ((Notes.StartsWith("A parent") || Notes.StartsWith("An ancestor") || Notes.StartsWith("This page") || Notes.StartsWith("This document")) && (Notes.EndsWith(" was moved") || Notes.EndsWith(" was renamed") || Notes.EndsWith("'s property 'umbracoUrlName' changed")))
```

**Comment by UmbracoNewb** [comment]
So 301 URL Tracker should leave a note in the Notes column every time? If I do a:

select count(*) from icUrlTracker where
Notes is null

I get over 1.000.000 rows returned. Guess I'm outta luck!
