### ISSUE TITLE
Issue on 7.4

### ISSUE THREAD

**Issue by mcgawn** [kipusoep/UrlTracker#115]
getting a weird issue after upgrading to Umbraco 7.4, any ideas? 

![screenshot at feb 19 15-43-37](https://cloud.githubusercontent.com/assets/1831895/13180280/b0c08d46-d71f-11e5-8242-be25e60a7efa.png)

**Comment by kipusoep** [comment]
HI @mcgawn, you're running into ASP.NET AJAX issues, so it seems your upgrade did not succeed. This isn't the place to get help for this situation, maybe StackOverflow or our umbraco?
