### ISSUE TITLE
Too wide in Umbraco 7.4.1

### ISSUE THREAD

**Issue by greystate** [kipusoep/UrlTracker#116]
Don't know if this is a browser issue, or a general CSS issue, but on my MacBook Pro 15" (1400×900) the dashboard doesn't fit, and no matter how I resize the browser window, the dashboard is always _just a little too wide_.

Screenshot:

![urltracker_wide](https://cloud.githubusercontent.com/assets/5463/13303664/e0a66730-db50-11e5-864f-1f44f32b6d04.png)

I tried looking in the Inspector but gave up when I saw `<iframe>` inside an `<iframe>`, which I guess has to do with the way Umbraco loads a UserControl, right? :-)

Great package, though! :+1:

**Comment by kipusoep** [comment]
This is an umbraco issue: http://issues.umbraco.org/issue/U4-3940
