### ISSUE TITLE
Simple Redirect doesn't work - Umbraco v7.4.1

### ISSUE THREAD

**Issue by greystate** [kipusoep/UrlTracker#117]
Because my site is being hammered with request like this:

`/panegui.asp?/SomeStupidOffer`
`/panegui.asp?/f=ioeur&d=kflkdf`

I have set up a rule like this:

<img width="504" alt="url-tracker" src="https://cloud.githubusercontent.com/assets/5463/13337388/5cb1c8ea-dc1b-11e5-9864-3c4ee768ceeb.png">

_(By the way, that **Created** timestamp is way off; should read something like **23:28:31** to be more accurate)_

But I keep getting the built-in 404 page (from IIS 8.5)

- I've already set the `trySkipIisCustomErrors` to `true` (it's false by default in 7.4.x which caught me by surprise).

Enabling Logging and Debug, I never see the actual incoming URL - and I get `UrlTracker HttpModule | URL is an umbraco reserved path or url, ignore request` in the logfile...

The **panegui.asp** page was a page that used to exist, which hackers had tampered with to return questionable content from other places on the 'net. In other words, the file doesn't exist, and no content has that name — nor is it listed in the `umbracoReservedPaths`/-`Urls` keys in **Web.config**

**Comment by greystate** [comment]
Arg... seconds after hitting the Create issue button, it dawned on me to test something: I tried requesting `/panegui.aspx` instead — redirected instantly.

So - it's actually just the .asp extension that Umbraco never gets to handle, right? Or is it the other way around (Umbraco sends it off to IIS without even looking at it?)

**Comment by greystate** [comment]
Adding the redirect in `UrlRewriting.config` solves this issue for me.

**Comment by kipusoep** [comment]
Thanks for the report! Adding a rule to the UrlRewriting.config is only a work-around, so I'm re-opening the issue.

**Comment by greystate** [comment]
Cool - thanks! :+1:

**Comment by greystate** [comment]
:100: Awesome - works great!
