### ISSUE TITLE
URL Tracker UI appearing in nested scrollbars

### ISSUE THREAD

**Issue by jattwood** [kipusoep/UrlTracker#119]
After upgrading umbraco to 7.3.8 and upgrading to Url Tracker 3.11, the UI is appearing in its own set of scroll bars withing the Umbraco Scrollbars: 
![image](https://cloud.githubusercontent.com/assets/6452616/13643626/c644f5c4-e5ef-11e5-8de3-e53c4c8e6cbb.png)

**Comment by kipusoep** [comment]
#116
