### ISSUE TITLE
Bad performance - Url Tracker

### ISSUE THREAD

**Issue by jacktinuss** [kipusoep/UrlTracker#120]
Hi there!

We are experiencing some huge performance issues on a customer running Umbraco v.6.1.6 and Url Tracker v.3.8

When Url Tracker is enabled - the request times for every resource are very long compared to the same request times when the Url Tracker is disabled (setting urlTracker:disabled to true in web.config).

A few examples:

xyz.local/CropUp/topimage/media/49174/picture.JPG: Url Tracker enabled : 209 ms - Url Tracker disabled : 5 ms

jquery.flexslider.js: Url Tracker enabled : 278 ms - Url Tracker disabled : 22 ms

ga-event-tracking.js: Url Tracker enabled : 640 ms - Url Tracker disabled : 41 ms

All in all this means that for normal page, the total load time with Url Tracker Enabled is: 1,75 seconds - and with Url Tracker disabled it is: 0,49 seconds.

We have tried emptying the icUrlTracker table and also made sure that the cache is cleared when testing. It doesn't help. We have also tried updating to the newest Url Tracker version without any luck.

Do you know what the problem can be?

It is really making the overall experience of the website very bad.

Thanks in advance!

**Comment by martinabrahams** [comment]
Hi @jacktinuss I have experienced the same issue. We ran a memory profile and found the following change to have a massive impact. In our scenario the site uses multiple domains. I've put a pull request in for this, you can see the change 

#105

**Comment by jacktinuss** [comment]
Wow!

That seemed to do the trick!

Loadtime on random page has gone from 1,6 seconds to 0,4 seconds.

Lodtime of random image has gone from 270 ms to 7 ms.
Thanks!

**Comment by kipusoep** [comment]
Thanks for reporting and fixing this. I wasn't able to look at it this week and won't be until week 12. 
But I'll merge the PR asap.

**Comment by jacktinuss** [comment]
Thanks!

Should it be safe for me to take newest commit on the master branch and include martinabrahams changes and deploy the dll to the production environment? I mean, should i do anything regarding the DB tables or anything else?

The production environment is currently running 3.8. - i guess the new version will be 3.11.something?

**Comment by kipusoep** [comment]
It will be 3.12 and what you're suggesting is safe as far as I can tell.

**Comment by martinabrahams** [comment]
@jacktinuss you're welcome.

**Comment by protherj** [comment]
Any chance you will be releasing an update for 3.12 this week?

**Comment by kipusoep** [comment]
No sorry, I'm unable to maintain this project at the moment. I need some contributers I guess...

**Comment by protherj** [comment]
How can we help with the package build?  Are there instructions or a batch process to run?

**Comment by kipusoep** [comment]
No instructions, just a VS solution, Github source control and a NuGet package.
