### ISSUE TITLE
URL Tracker data type no longer exists?

### ISSUE THREAD

**Issue by StateBarofArizona** [kipusoep/UrlTracker#132]
Version 1.3 had a 301 URL Tracker data type that I was able to add to my master doc type.  This was very handy for allowing content authors to add their own custom redirects.  Where is the ability in version 3.x?

**Comment by granthughes** [comment]
The data type does not exist in version 3.

Watch issue #83 for further developments on the data type. If you would like to build the data type and create pull request, that would be great.
