### ISSUE TITLE
Installing via Nuget doesn't work

### ISSUE THREAD

**Issue by fatboytim2000** [kipusoep/UrlTracker#134]
I've just tried installing UrlTracker for the first time. I took the Nuget approach, and the Nuget part appeared to complete successfully.
I was then presented with the Readme.txt - indicating that I now needed to open Umbraco in order for the installation to complete.
I then went into Umbraco backoffice - and nothing at all happened. No new sections, nothing new on the dashboard, nothing new at all as far as I can see.
My website is source-controlled, so I then tried checking out all of the /Config folder files, on the off-chance they needed to get updated and were read-only, but still nothing, even after Restarting the app-pool several times.

Umbraco version 7.4.3.

Thanks
Tim

**Comment by kipusoep** [comment]
Did you rebuild the solution, like mentioned in the readme?

**Comment by fatboytim2000** [comment]
Yep, several times

**Comment by granthughes** [comment]
Did you ever previously have this plugin working? If the icUrlTracker table exists in your database when firing up the app, then the plugin will not go through its complete setup process. The existence of the table tells the plugin that it has already been set up.

Give either of these items a try:

- Delete the icUrlTracker table from your database and then restart your app

OR
- Add the following to Config/Dashboard.config within the StartupDashboardSection section:

`<tab caption="Url Tracker">
<control addPanel="true">~/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx</control>
    </tab>`

**Comment by bjarnef** [comment]
I just needed to add the following to dashboard.config after installing UrlTracker via NuGet:

```
<section alias="StartupDashboardSection">
    <areas>
        <area>content</area>
    </areas>
    <tab caption="Url Tracker">
        <control addPanel="true">~/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx</control>
    </tab>
</section>
```
