### ISSUE TITLE
Rename tracking not working if page doesn't have a template

### ISSUE THREAD

**Issue by mihaelav** [kipusoep/UrlTracker#154]
Hi,

Is there a reason why redirects are added for rename/move events only if the page has a template? We're not using templates because we're using a custom folder structure so at the moment every time a page is renamed/moved we need to manully add a redirect rule.

Thanks

**Comment by kipusoep** [comment]
Because when a page doesn't have a template, it's not viewable through any URL at all. So it doesn't make sense to create a redirect for a URL which doesn't have a page attached to it.
