### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by GambitKZ** [kipusoep/UrlTracker#157]
Hi, guys!

Is this project still alive?
The last update was 6 months ago. Can we expect any changes or this project is abandoned?

**Comment by mortenmoulder** [comment]
If you have any suggestions, I think you should make them. I love this package already and I can't see what I there is to add anymore. I see the author (@kipusoep) commenting on issues here, so I assume it's still active.

**Comment by GambitKZ** [comment]
Well, there are 4 pull requests which hang there from the 2015 year.
Also, there are 30+ issues in the issue tracker which were not closed.
So all of this make me think that it is the case...

**Comment by kipusoep** [comment]
And you're absolutely right tbh...
