### ISSUE TITLE
Create 301 url with .html extention

### ISSUE THREAD

**Issue by rasmuseeg** [kipusoep/UrlTracker#16]
We are having issues with the Create option, not working for "sample.html" in the url.
The link to the right of the box, shows: "http/sample.html"
and not: "http://ourdomain.com/sample.html"

Umbraco 7.1.4

We found that adding the urls from the Not found view, worked, for now.

**Comment by kipusoep** [comment]
Can you reproduce this issue with v3.5?

**Comment by kipusoep** [comment]
No reply, so closing.
