### ISSUE TITLE
Compatibility with Umbraco 7.6.3

### ISSUE THREAD

**Issue by blachawk** [kipusoep/UrlTracker#161]
In regards to Umbraco 7.6.3. /Config/UrlRewriting.config  has been removed.  Does this impact the performance of this package for this version of Umbraco? If so, what changes?

**Comment by daniel-chenery** [comment]
AFAIK this doesn't use UrlRewriting, and it's working fine on 7.6.x sites for me. Do let me know if you run into any problems though...
