### ISSUE TITLE
Excessive INFO logging from nuget v3.13.0

### ISSUE THREAD

**Issue by PhilDye** [kipusoep/UrlTracker#165]
The built version released in v3.13.0 (from nuget) appears to have an extra `LogHelper.Info` in `LoggingHelper.LogInformation` - this method normally logs at level DEBUG only.

Verified by building from current source, which no longer logs at INFO, and inspection of nuget-released DLL using DotPeek.

**Comment by PhilDye** [comment]
Decompiled nuget v3.13.0 method; note extra `LogHelper.Info` call;

```
public static void LogInformation(string message)
    {
      LogHelper.Info(typeof (LoggingHelper), message, new Func<object>[0]);
      if (!UrlTrackerSettings.EnableLogging)
        return;
      LogManager.GetLogger(typeof (LoggingHelper)).Debug((object) message);
      LogHelper.Debug(typeof (LoggingHelper), (Func<string>) (() => message));
      UrlTrackerLogging.Log(message);
    }
```

**Comment by daniel-chenery** [comment]
@PhilDye Doh! That would be some left over test code for always force logging. Will remove and update shortly 🙄 

Thanks!

**Comment by PhilDye** [comment]
@daniel-chenery I'm guessing the AppVeyor build isn't automatically releasing to nuget?

**Comment by daniel-chenery** [comment]
@PhilDye Nope :(

**Comment by daniel-chenery** [comment]
@PhilDye The correct build should be on NuGet now.

I'll look into the AppVeyor stuff - thanks!
