### ISSUE TITLE
Regex redirects failing after Umbraco and UrlTracker version updates

### ISSUE THREAD

**Issue by levipatel** [kipusoep/UrlTracker#170]
I recently updated Umbraco from version 7.4 to 7.6.5. Following that I also updated the UrlTracker to version 3.13.1. I'm not certain but I believe the previous version we had was 3.12.

Following these updates, any regex based redirects have been failing with a 404 error generated by the browser (not our site's custom 404 page). The only regex redirects that sometimes succeed have the Force Redirect attribute set to true, though results are still very inconsistent.

Unfortunately I didn't test the redirects in the time between updating Umbraco and updating UrlTracker so I can't be sure which update led to the issue.

Any help would be much appreciated!

Thanks,
Levi

**Comment by daniel-chenery** [comment]
Hmm, the Regex site of things haven't been altered.

Can you try creating a new Regex redirect and tell me if that works. Could you also give me an example of a failing Regex, I'll see if I can replicate it

**Comment by levipatel** [comment]
I created two new Regex redirects and they both work without any issues.

Here are a few examples of failing redirects along with a link that used to be redirected by them:

Test link: http://help.cin7.com/prod.asp?idWebPage=70305&ID=886&SID=496178538
Regex: [&|?]ID=886
Force redirect = false

Test link: http://help.cin7.com/prod.asp?idWebPage=70305&ID=800&SID=729994868
Regex: [&|?]ID=800
Force redirect = false

Test link: http://help.cin7.com/prod.asp?idWebPage=70305&ID=1055&SID=4405206
Regex: [&|?]ID=1055
Force redirect = true


Strangely, one of the first links that we noticed was broken seems to be working again. Here are the details for that one:

Test link: https://help.cin7.com/prod.asp?idWebPage=70305&ID=1056&SID=4556638
Regex: [&|?]ID=1056
Force redirect = true

**Comment by daniel-chenery** [comment]
@levipatel thank you. If you save the redirect again, does it randomly start working?

**Comment by levipatel** [comment]
I just resaved the ID=800 redirect and had no luck unfortunately.

**Comment by levipatel** [comment]
Something else I noticed is that the Url Tracker interface has been extremely slow recently, sometimes even timing out while loading the page or searching for a redirect.

I wondered it if might be related, perhaps if the issue was database related and it was having trouble retrieving the old records or something like that.

**Comment by daniel-chenery** [comment]
@levipatel There are a few performance issues with 3.13 :(
Please try the latest 3.14 BETA, hopefully they're improved with that...

I haven't been able to replicate your issue yet, so I'd be surprised if it fixed your Regex issues

**Comment by levipatel** [comment]
@daniel-chenery The performance is still quite slow in 3.14 Beta but it is definitely more useable now.

We have decided that we will simply recreate the more important regex redirects that we previously had in place, rather than spending more time trying to solve the underlying issue. Hopefully we can resolve it properly in the future but that should keep us going for now.

I really appreciate your time and advice.

**Comment by levipatel** [comment]
@daniel-chenery I found another piece of information that may or not be of interest.

![screen shot 2017-10-05 at 1 58 00 pm](https://user-images.githubusercontent.com/2025536/31207235-84c95180-a9d9-11e7-9b30-4c7678d14b38.png)

The top row is an old, broken redirect. The bottom row is a newly created redirect that works.

The only difference I can see is that the size of the Id numbers has become much larger with the new entries. Do you think that could be related to this issue?

**Comment by daniel-chenery** [comment]
@levipatel Does any node with t he ID of 6659 exist? If it doesn't, and the Node ID has changed, then that will explain why the redirect isn't working. It has nowhere to redirect to

**Comment by levipatel** [comment]
@daniel-chenery Unfortunately for our investigation, a node does exist with that ID.

**Comment by daniel-chenery** [comment]
@levipatel I'm guessing the node 6659 is published also? :)

Unfortunately I'm out of ideas as to why it's no longer redirecting. Especially since they work when re-created

**Comment by levipatel** [comment]
@daniel-chenery Yes it is published.

That's okay, we've been able to get things working well enough by recreating the important redirects. Ideally we would have been able to fix the old ones but this is good enough to go on with.

Thanks for taking the time to look into it!

**Comment by daniel-chenery** [comment]
@levipatel Since we've exhausted ideas, I'm going to close this. But do feel free to come back if it returns...
