### ISSUE TITLE
Redirect existing node to another existing node

### ISSUE THREAD

**Issue by jimbacha** [kipusoep/UrlTracker#176]
Looking to redirect an existing node to another existing node. Is this possible? 

ie. /products/category/    >    /products/category/product-detail-1

Running 7.7.4 with version 3.14

**Comment by daniel-chenery** [comment]
If you check "Force Redirect" it should redirect, even if a page is found

**Comment by jimbacha** [comment]
Appreciate the quick response, that isn't working for me. 

Even to a third party site, want /privacy-policy to go to google.com/privacy, no dice. Still straight to my local privacy policy. Seems to only work when there isn't an existing node currently.

**Comment by daniel-chenery** [comment]
I had a horrible feeling you were going to come back with that response :(

Could you make use of the UmbracoUrlAlias field?

**Comment by jimbacha** [comment]
In a strange turn of events, I removed UrlTracker via nuget and installed via the Umbraco back office package manager which installed 3.1.1 and all is working for third-party and existing node to existing node.

**Comment by daniel-chenery** [comment]
All fixed :) [https://www.nuget.org/packages/UrlTracker/3.14.1](https://www.nuget.org/packages/UrlTracker/3.14.1)
