### ISSUE TITLE
Double Slashes in v3

### ISSUE THREAD

**Issue by vtml** [kipusoep/UrlTracker#18]
Hi,

This is my entry in the database.
OldUrl: Latitudes
RedirectUrl: global/en/?dsc=234
RedirectHttpCode: 301
RedirectPassThroughQueryString: 1
Is404: 0
ForceRedirect: 0

The site only has one domain and umbracoDomains table is empty.

When I type in http://somehost.com/Latitudes, it redirects to http://somehost.com//global/en/?dsc=234 (with a double slash after the host name).

Please help.

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by kipusoep** [comment]
No reply, so closing.
