### ISSUE TITLE
Clean previous not found (404) requests tracked from database

### ISSUE THREAD

**Issue by pnmcosta** [kipusoep/UrlTracker#180]
I've inherited a Umbraco  7.2.8 that is running the package v3.9.

The previous developers had the site with urlTracker:notFoundTrackingDisabled disabled/false since 2015.

I'm now hoping to delete all previous 404 tracks from the database that has over 1M records at the moment.

Can anyone point at the columns I should be filtering the table with? Due to the high number of records, I'm going to copy over to a temp db the records I'd like to keep (non 404 tracks), truncate the original table and then re-insert.

Thank you so much.

**Comment by daniel-chenery** [comment]
Hi,

All entries are stored in the `icUrlTracker` table. Redirects, and 404s.
You can filter out 404 requests with the `is404` column

Example:
```
SELECT *
FROM icUrlTracker
WHERE Is404 = 1
```

**Comment by pnmcosta** [comment]
Awesome, thought so :) 

Thanks so much, here's the truncate script if anyone interested:

```sql
select *
into #temp_icUrlTracker
from icUrlTracker where Is404 = 0
 
truncate table icUrlTracker
 
SET IDENTITY_INSERT icUrlTracker ON
 
insert into icUrlTracker ([Id]
			,[OldUrl]
           ,[OldUrlQueryString]
           ,[OldRegex]
           ,[RedirectRootNodeId]
           ,[RedirectNodeId]
           ,[RedirectUrl]
           ,[RedirectHttpCode]
           ,[RedirectPassThroughQueryString]
           ,[ForceRedirect]
           ,[Notes]
           ,[Is404]
           ,[Referrer]
           ,[Inserted])
 select * from #temp_icUrlTracker
 
SET IDENTITY_INSERT icUrlTracker OFF
 
DROP TABLE #temp_icUrlTracker
```

Use at your own peril
