### ISSUE TITLE
Url tracker writes null on RedirectNodeId in db

### ISSUE THREAD

**Issue by borgchrist1** [kipusoep/UrlTracker#192]
Hi
On my clients site 301 url tarcker has written null on all redirects to column RedirectNodeId and 1 on Is404. If i check force redirect it starts working and writes the correct nodeid to RedirectNodeId and changes Is404 to 0.
Is there a way to fix this?
You can close this since I guess is settings related.

**Comment by daniel-chenery** [comment]
If it's a 404 page, then this is expected.
The RedirectNodeId is the ID of the page to **redirect to**

The `Is404` column is just for logging 404's
