### ISSUE TITLE
Compatibility with Umbraco 8.x

### ISSUE THREAD

**Issue by marcusjm** [kipusoep/UrlTracker#201]
This is one of the reasons I hesitate to use 8.x yet. Is this part of the roadmap?

**Comment by helenahedstrom** [comment]
I'm curious about this too! We use this package a lot, so much that I've started working on my own with the same functionality. But if it's already in the making then maybe I could work on something else instead :)

**Comment by stefankip** [comment]
https://github.com/kipusoep/UrlTracker/issues/135

**Comment by kipusoep** [comment]
https://github.com/kipusoep/UrlTracker/issues/135
