### ISSUE TITLE
404 Not Found View CSS

### ISSUE THREAD

**Issue by JBoye** [kipusoep/UrlTracker#27]
The 404 View does not look good with long URLs. 

![urltrackerbefore](https://cloud.githubusercontent.com/assets/5902488/4148387/7523a218-3424-11e4-8464-16f83c1a9e2b.png)

Using the Chromes web inspector, i added these lines to **td**

    text-overflow: ellipsis;
    white-space: nowrap;
    max-width:400px;
    overflow: hidden

After:
![urltrackerafter](https://cloud.githubusercontent.com/assets/5902488/4148388/752c5bf6-3424-11e4-9b3d-5a2e82bd4309.png)

**Comment by kipusoep** [comment]
Thanks for the suggestion. I've included it in v3.5.
Next time it would be cool if you could create a Pull Request ;-)
