### ISSUE TITLE
JavaScripts errors in backend in IE11

### ISSUE THREAD

**Issue by abjerner** [kipusoep/UrlTracker#31]
Hi Stefan - and first of all, thanks for a great package ;)

UrlTracker loads its own version of jQuery (version 1.10.1) instead of using the version already bundled with Umbraco (1.7.2 in Umbraco 6.1.x).

jQuery 1.10.1 apparently doesn't play nice with IE11. See the following screenshot for further information:

![image](https://cloud.githubusercontent.com/assets/3634580/4574167/2668f7fe-4f9a-11e4-8e69-39d409815cd8.png)

This results in IE stopping to execute remaining JavaScript - eg. in other tabs in the dashboard. Is there any reason for loading another version of jQuery? The errors stop showing up if I disable the tab in the dashboard.

Please let me know I you need any further information to investigate this ;)

Thanks in advance,
Anders Bjerner

**Comment by kipusoep** [comment]
Updating to jQuery 1.11.2 fixed this, will be included in the next release.
Thanks for reporting and sorry about the delay!
