### ISSUE TITLE
Multiple domains bug

### ISSUE THREAD

**Issue by ioagiannis** [kipusoep/UrlTracker#33]
Hello,
I am facing the problem described below:
I have two websites on a single umbraco installation.
Every website has its own domain name.
I am using UrlTracker to redirect urls for both websites.

This is my content tree, where you can see the two Root nodes (every root node has its own domain)
![capture](https://cloud.githubusercontent.com/assets/9035338/4733252/1d4d86c2-59c6-11e4-9856-b6925ab9a681.PNG)

It seems that UrlTracker works only for the first (in order) Root node of the content tree. Url Tracker redirects only the urls of the first Root node and ignores the redirection urls of the second Root node.

Is there any idea ?

Thank you.

Using versions:
UrlTracker version: 3.0.1 
Umbraco version: 6.1.6

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by kipusoep** [comment]
No reply, so closing.
