### ISSUE TITLE
Issue using Url Tracker with deployed site.

### ISSUE THREAD

**Issue by KalidSalim** [kipusoep/UrlTracker#34]
Hi there,
I am having some trouble with the Url Tracker.
When the site is hit for the first time, i.e on first load or after a reset of the app pool, the following error can occur:

Server Error in '/' Application.
________________________________________
Value cannot be null.
Parameter name: virtualPath 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: virtualPath

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace: 
 
[ArgumentNullException: Value cannot be null.
Parameter name: virtualPath]
   System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options) +9829401
   System.Web.VirtualPathUtility.ToAbsolute(String virtualPath, String applicationPath) +43
   Umbraco.Core.IO.IOHelper.ResolveUrl(String virtualPath) +137
   InfoCaster.Umbraco.UrlTracker.Helpers.UmbracoHelper.IsReservedPathOrUrl(String url) in c:\Users\kipusoep\Documents\GitHub\UrlTracker\Helpers\UmbracoHelper.cs:48
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in c:\Users\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:98
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_AcquireRequestState(Object sender, EventArgs e) in c:\Users\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:53
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

If the page is refreshed/ the site is loaded again, the problem resolves itself. 
I would like to request some guidance on how to solve this issue. 
It seems to be very similar to the bug you resolved for v2.4. But the current Url tracker I am using is v3.1.

I am trying to get this isue resolved as soon as possible so any help would be benificial.

Thank You.

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by ahenriksen11** [comment]
I'm still getting this same error. Running version 3.9.

**Comment by ahenriksen11** [comment]
This post below helped me. I had a space in one of my reserved paths.

https://our.umbraco.org/projects/developer-tools/301-url-tracker/version-2/56639-Error-during-install-on-714
