### ISSUE TITLE
Installation failures

### ISSUE THREAD

**Issue by mathijsb85** [kipusoep/UrlTracker#41]
Hi!

Couldn't get the package installed at all on U6.2.4 using UT 3.2. Table was missing column "ForceRedirect". Al recource files weren't copied and file references were made to "UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.aspx".

Any idea? :-)

Mathijs

**Comment by kipusoep** [comment]
No reply, so closing.
