### ISSUE TITLE
I'm having a problem creating a redirect from a non existent page

### ISSUE THREAD

**Issue by IAMMRBONGO** [kipusoep/UrlTracker#45]
On one of my sites I try creating a redirect for /scruffts/  this is a page off of an old website. I try to redirect to a URL but there is a problem. No error message is returned but the following page appears:

http://our.umbraco.org/media/upload/3b41a246-7073-488c-ad8d-57b8b14764c1/scrufts-redirect.png

Any ideas what I am doing wrong here? is there any way that I can locate the error message?

Umbraco version 7.1.6 is the version I am using

**Comment by lukealderton** [comment]
Looks like you've got both a redirect node and a url chosen, I had this issue. Use one or the other, the error message is a bit misleading.

**Comment by kipusoep** [comment]
Like @lukealderton said, it's a user issue.
