### ISSUE TITLE
"Remove at" not working properly with UrlTracker

### ISSUE THREAD

**Issue by abjerner** [kipusoep/UrlTracker#49]
I have an Umbraco installation running 6.1.6 with UrlTracker 3.0.

Whenever a user sets a "Remove At" date for a given page, everything seems to work fine when looking in the backoffice. When the date is passed, the page correctly appears to have been unpublished according to the UI on the backoffice. However in the frontend, the page seems to still be existing in the content cache.

Steps to reproduce:
* Create a page
* Set "Remove At" date and publish the page
* Wait... 
* Page is still accessible via the frontend after the date has passed

I tried upgrading to UrlTracker 3.2, but the page still isn't unpublished properly if I retry the above steps.

If I try to remove the UrlTracker DLL, the page is unpublished correctly.

**Comment by abjerner** [comment]
Hi Stefan,

Any news regarding this issue?

**Comment by kipusoep** [comment]
Not yet.

**Comment by kipusoep** [comment]
I've fixed this and tested with umbraco v7.2.1, works perfectly :-)
Will be included in the next release.
