### ISSUE TITLE
Handling Multiple Domains 

### ISSUE THREAD

**Issue by akeilox** [kipusoep/UrlTracker#51]
I am using 301 tracker for changed pages, which works quite well.
Recently I have binded 5 different domains to the same site in IIS,  and would like to do forwarding like

abc.domain.com => domain.com/a-new-home
xyz.domain.com/.* => domain.com/xyz/.*

Is this possible with urltracker? When i enter http://abc.domain.com and destination as domain.com/a-new-home  (in tracker interface)
it doesnt seem to work. 

Would much appreciate if you can share your experience in achieving the above (for multiple domains) and still using 301 tracker.

cheers

**Comment by kipusoep** [comment]
Unfortunately that's not possible with the UrlTracker. It's far too complicated for it, so I'd recommend using rewrite rules for this.

**Comment by akeilox** [comment]
thanks for the prompt reply. Is there any issue with using URL rewrite tool with 301 concurrently?
Never used url rewrite before, so not sure.

**Comment by kipusoep** [comment]
It'll work side-by-side. URL Rewrite is executed first afaik.

**Comment by akeilox** [comment]
Thats great! Can I check real quick for abc.domain.com to domain.com/a-new-home example
would it be considered redirect or rewrite from the URL rewrite module?

**Comment by kipusoep** [comment]
http://www.iis.net/downloads/microsoft/url-rewrite

**Comment by akeilox** [comment]
thank you!
