### ISSUE TITLE
A lot of calls to the database

### ISSUE THREAD

**Issue by JohanLars** [kipusoep/UrlTracker#55]
I have installed the 301 URL Tracker version 3.3 on my Umbraco 7.1.6 site, when running an SQL profiler to see all SQL calls that my system do to the database I can find a lot of calls to the icUrlTracker database table. Should not these calls be cached? Or have I missed something?

The SQL command that is sent may differ from 20 to 50 times per Umbraco page, and every call is exactly the same:

exec sp_executesql N'SELECT * FROM icUrlTracker WHERE Is404 = 0 AND ForceRedirect = @forceRedirect AND RedirectRootNodeId = @redirectRootNodeId AND OldRegex IS NOT NULL ORDER BY Inserted DESC',N'@forceRedirect int,@redirectRootNodeId int',@forceRedirect=1,@redirectRootNodeId=1076

**Comment by tgriley** [comment]
We've just started using it and its very chatty indeed. I've added some sql query caching in a fork that ill  submit a pull request for once it is through testing.

**Comment by kipusoep** [comment]
Looking forward to it @tgriley!

**Comment by tgriley** [comment]
Finished dev today so hopefully ill throw it your way by the end of the week. PS, that was a fast reply!

**Comment by xumix** [comment]
Any news? I'm using v3.7 and still see this:
![2015-05-15 15 40 23 iis server - 15 05 2015 15_36_00 jetbrains dottrace performance viewer administrator](https://cloud.githubusercontent.com/assets/250118/7652783/bcadd778-fb18-11e4-93b5-1f5a8b3e0b5a.png)

**Comment by kipusoep** [comment]
No news yet, but the screenshot is a good wake-up call. Thanks for the heads up and I'll look into it!

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by xumix** [comment]
Well, that's better, but still kinda slow 
![2015-05-26 11 30 25 w3wp exe - 26 05 2015 11_26_54 jetbrains dottrace performance viewer administrator](https://cloud.githubusercontent.com/assets/250118/7808277/b004b44e-039a-11e5-9e92-ab27125ccc59.png)

**Comment by kipusoep** [comment]
Thanks @xumix, but I'm not sure what's slow about this. Could you explain a bit about the screenshot?

**Comment by xumix** [comment]
@kipusoep well, it is not slow, it is **slowish** :)
As for me, 32ms just to check&get redirect url is too much. I'd cache all redirect nodes as Dictionary<int, string>. Then you could just use this map, refreshing it as needed.

**Comment by kipusoep** [comment]
@xumix That's not a very good idea imo when there can be loads of entries... And 32ms isn't slowish world to be honest.

**Comment by kipusoep** [comment]
No reply, so closing.
