### ISSUE TITLE
Invalid column name 'ForceRedirect'

### ISSUE THREAD

**Issue by shearer3000** [kipusoep/UrlTracker#57]
hi - I received this error trying to install Url Tracker 3.4 over the top of version 2.2.6. This was on Umbraco 6.1.6.

Invalid column name 'ForceRedirect'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'ForceRedirect'.

**Comment by kipusoep** [comment]
Same issue as #21.
Did you use SQL CE?

**Comment by shearer3000** [comment]
no not SQL CE, we use SQL server 2008R2

**Comment by kipusoep** [comment]
I haven't been able to reproduce this issue, so I'm not sure what to do next...

**Comment by dillorscroft** [comment]
Hi... I get this too.  The scripts in the SQL folder add ForceRedirect initially but a subsequent update removes it.

**Comment by kipusoep** [comment]
@dillorscroft what do you mean exactly with "a subsequent update removes it"?

**Comment by kipusoep** [comment]
No reply, so closing.

**Comment by dillorscroft** [comment]
@kipusoep Sorry.  I can't recall the issue either. ;-(

**Comment by kipusoep** [comment]
No problem, just cleaning up :-)
