### ISSUE TITLE
Error after upgrading from 3.0.1 to 3.4 - "invalid field UrlTrackerInfoUrl"

### ISSUE THREAD

**Issue by gfyans** [kipusoep/UrlTracker#58]
Hi,

I upgraded from 3.0.1 to 3.4 and I'm now getting the following error in the dashboard:

```
Error creating control 
System.MissingFieldException: Field not found: 'InfoCaster.Umbraco.UrlTracker.UrlTrackerResources.UrlTrackerInfoUrl'. at ASP.umbraco_urltracker_infocaster_umbraco_urltracker_ui_urltrackermanagerwrapper_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at umbraco.uicontrols.PropertyPanel.Render(HtmlTextWriter writer) in d:\Dev\Umbraco6\src\umbraco.controls\Property.cs:line 38
```

Running Umbraco 6.2.1.

Any ideas? It was working fine on 3.0.1.

**Comment by kipusoep** [comment]
Weird thing is; the field is still there...
Some questions:
* How did you upgrade (NuGet / Umbraco back-office)?
* Is the 'InfoCaster.Umbraco.UrlTracker.dll' file in your \bin folder?
* Can you post your version of the 'InfoCaster.Umbraco.UrlTracker.dll' file somewhere, so I can have a look at it?

**Comment by gfyans** [comment]
Hi,

Yea I can still see the field so a bit of a puzzler.

* I downloaded the latest package from Our and upgraded via Umbraco back-office
* Yes, along with the .pdb
* Sure, here you go http://goo.gl/zxJ9ts

FYI, other packages I have installed, just in case you know of any conflicts:

![image](https://cloud.githubusercontent.com/assets/1040786/6104253/986dd658-b043-11e4-8ed2-cc9d5bfeb53c.png)

Just a few :)

**Comment by kipusoep** [comment]
I'm not sure what to do next... The field is there, it works for me.
The line in question is:
````<a style="position: absolute; top: 10px; right: 14px;" target="urltracker" href="<%= UrlTrackerResources.UrlTrackerInfoUrl %>">````

So it seems in your situation that the class 'UrlTrackerResources' isn't resolve correctly, but why?

**Comment by gfyans** [comment]
Hmm, I'll try uninstalling the one I have and install a fresh one. Give me a few mins...

**Comment by gfyans** [comment]
OK, that was longer than a few mins but I had to try a few things.

And, aaaaaaaaaaaaaaaagh! I figured out what was wrong. Nothing to do with UrlTracker, everything to do with ASP.NET not recycling it's Temporary Internet Files for this assembly, for some unknown reason.

I had to stop the app pool and delete the Temp ASP.NET Files folder to force it to load in a fresh copy.

Sometimes I hate .NET.

**Comment by kipusoep** [comment]
Thanks for letting me know, glad it works! Enjoy :+1:
