### ISSUE TITLE
Redirect expiry date

### ISSUE THREAD

**Issue by UmbracoNewb** [kipusoep/UrlTracker#59]
I think it would be a good feature to be able to define an expiry date on a redirect. Most redirects naturally expire after a periode of time and is just filling up the database and UI. So if expiry date exceeded, then delete the record :-) Maybe an addition of a LastUsed timestamp would be useful

**Comment by kipusoep** [comment]
How often do you think the expiry date feature will be used? I think it isn't worth the time I'll have to invest in building this, but I'd like to know what others think about this too.

**Comment by gfyans** [comment]
Hi Stefan,

The last used timestamp would be useful from a point of view of maintaining a clean DB. It would be good to be able to run a query against the 404s and 301s and prune any that haven't been used for a while.

**Comment by kipusoep** [comment]
Yes I agree, but what about performance? Every time a redirect is executed I need to write to the database.
And 301 Moved Permantently responses are thoroughly cached by the browser, so the last used timestamp won't be reliable.

**Comment by kipusoep** [comment]
No reply, so closing.
