### ISSUE TITLE
domain url cannot contain http://

### ISSUE THREAD

**Issue by EnterpriseWide** [kipusoep/UrlTracker#61]
when my site has the url for domain in the culture and domains editor set to a value that begins with http:// , url tracker doesn't handle it and fails. When I remove the http:// and just leave the domain value set to example.com it all starts working again. This was unexpected behaviour. Can you allow for either  in a future release.

**Comment by kipusoep** [comment]
* What version of the UrlTracker are you using?
* Do you have a screenshot of the hostnames configuration?

**Comment by kipusoep** [comment]
No reply, so closing.
