### ISSUE TITLE
redirects not taking effect

### ISSUE THREAD

**Issue by alexh22** [kipusoep/UrlTracker#63]
Hi,

I was trying to add this package to my solution ( I run Umbraco 7.1.9), and while the interface loads properly and allows me to set everything the way I would like, the redirects just never occur.

Could someone point me out to instructions which a bit more content than the readme of the package. Or better yet, in the event any of you experienced the same issue, any leads on solutions?

Any ideas would be much appreciated.

Cheers.

**Comment by kipusoep** [comment]
Have you seen #62, this issue just before this one?
