### ISSUE TITLE
Umbraco 7.1.6 running on Azure URL Tracking

### ISSUE THREAD

**Issue by gsvavarsson** [kipusoep/UrlTracker#68]
Hey, just wanted to point out (since you say Azure compatibility is untested), that I can't get the URL trackers to work on my setup. It might be that I'm new to 301 tracker. But I'll leave a screendump of one of my trackers here. http://i.imgur.com/qylamJe.png

br. 
Gisli

**Comment by kipusoep** [comment]
Have you tried the redirect on a non-azure environment?

**Comment by gsvavarsson** [comment]
Yes, but only on Umbraco 6.* not 7. We use Azure for all of our installations now.

**Comment by kipusoep** [comment]
And did it work on the non-azure environment? Can't think of any reason why it shouldn't work on azure...

**Comment by gsvavarsson** [comment]
Yes is works on non-azure. but like is said that is umbraco 6 not 7 like the new installation. You can see that this (http://www.icelandtours.is/en/vacation-packages-to-iceland/self-drive-tours-in-iceland) link should take you to this page (http://www.icelandtours.is/en/vacation-packages/?type=self_drive).
But it lands on the first link which returns a 404 site. 
I know when you're setting up a custom 404 site in Umbraco Azure then you have to set a <httpErrors> tag in web.config, so that the browser can detect it.  
![icturltracking](https://cloud.githubusercontent.com/assets/9461240/6663984/8abff2f2-cbc3-11e4-990f-72c900e37945.PNG)

**Comment by kipusoep** [comment]
I think the Old URL isn't right. The domain is already "domain/**en**" and the Old URL starts with "**en**/" too...
Could you try removing the "**en/**" part of the Old URL?

**Comment by gsvavarsson** [comment]
that worked I had tried it before but since the link-icon on the right of
the old link didn't consider the /en that threw me off.
thanks for your help mate.

On Mon, Mar 16, 2015 at 10:07 AM, Stefan Kip <notifications@github.com>
wrote:

> I think the Old URL isn't right. The domain is already "domain/*en*" and
> the Old URL starts with "*en*/" too...
> Could you try removing the "*en/*" part of the Old URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kipusoep/UrlTracker/issues/68#issuecomment-81556541>.
>



-- 
kveðja/best regards
Gísli Freyr Svavarsson
Vef-forritari/Web-Programmer
Odin Software
gisli@odinsoftware.is
