### ISSUE TITLE
UrlTracker won't redirect to new URL after pages has been renamed

### ISSUE THREAD

**Issue by abjerner** [kipusoep/UrlTracker#69]
I can't tell whether this relates to one of the existing issues, so here goes.

I have a client with a solution running Umbraco 6.1.6 and UrlTracker 3.5. The solution uses an Azure SQL database. If I rename a page, the old URL isn't redirecting the user to the new URL.

To test this further, I tried setting up a fresh installation of Umbraco 6.1.6 and UrlTracker 3.5. This time with a SQL CE database though.

The content tree looks like:

![image](https://cloud.githubusercontent.com/assets/3634580/6748788/19dfa49a-ceea-11e4-9e47-41a162d8db68.png)

The page `Hello World` was originally named `Hej med dig`, but accessing `http://urltracker1.omgbacon.dk/hej-med-dig.aspx` just returns a 404 error as if UrlTracker wasn't installed.

The same is the case for the page `This is definitely a page` under the other site. The page was originally named `This is a page`, but `http://urltracker2.omgbacon.dk/this-is-a-page.aspx` also just returns a 404 error.

Both these pages are direct children of a site node (with configured host names). If I change the name of a node, that is a descendant, but not a direct child, it appears to be working correctly.

For all three pages, a redirect is saved to the database, and visible in the dashboard. The difference seems to be that for the direct children, the site is set incorrectly. If you see the screenshot below, the second and third entries have the site set to the node that I edited, whereas for the first entry, the site is set correctly.

![image](https://cloud.githubusercontent.com/assets/3634580/6748890/0cc226ba-ceeb-11e4-8585-755197e34bc7.png)

I have enabled logging, but there doesn't appear to be anything related to UrlTracker for the redirects, that don't work.

**Comment by kipusoep** [comment]
Thank you very much @abjerner for the detailed bug report :+1: 
I think this *is* related to other bug reports, but I'm afraid I can't reproduce it easily.
Would it be possible to get a copy of the website and database so I can run a debug session?

**Comment by abjerner** [comment]
Hi Stefan and thanks for a quick answer,

Here is a ZIP of the test solution:
https://www.dropbox.com/s/1l8mv6xql3ic284/UmbracoCms.6.1.6.zip?dl=0

The username for the backoffice is `skybrud` and the password is `1234`.

**Comment by kipusoep** [comment]
Thanks! I'll get back to you about it today!

**Comment by kipusoep** [comment]
Try v3.6 :-)

**Comment by abjerner** [comment]
Sorry for not being able to test and answer sooner. The fix works like a charm - thanks a lot ;)

:+1:

**Comment by meto5000** [comment]
I don't think this fixes the issue (or potentially introduced a new issue for Umbraco 7.1.2).

I've uploaded some images that explain the problem but here is the gist:

* Create new redirect within Url Tracker
* Link does not redirect
* Editing the link and clicking "Advanced Mode" gives an error (see image)
* Link now appears in the 404 Not Found View
* Creating a redirect from the link inside 404 Not Found makes a redirect link that works properly
* User created links within the Url Tracker View show the Site as "Home"
* Redirect links created from the 404 Not Found View show the Site as a blank field
* In the sql db, the links from the 404 have -1 as RedirectRootNode vs 1055 for User created redirect links

http://imgur.com/a/r7SiP
