### ISSUE TITLE
Exception on install - v3.6, Umbraco 7.2.4

### ISSUE THREAD

**Issue by gfyans** [kipusoep/UrlTracker#70]
Hi, I'm currently receiving the following exception after the browser is reloaded when you install the package:

![image](https://cloud.githubusercontent.com/assets/1040786/6827012/fbe2b4de-d2fc-11e4-83b8-bbe8c48670d5.png)

This is the URL it is trying to load:

/umbraco/#/developer/framed/%252Fumbraco%252Fdeveloper%252Fpackages%252Finstaller.aspx%253Finstalling%253DcustomInstaller%2526dir%253DD%253A%255CProjects%255CMDDUS%255CWebsite2015%255CMDDUS.Umbraco%255CMDDUS.Umbraco%255CApp_Data%255C8dfbc319-79e8-4ad2-b955-d155d0cff976%2526pId%253D1%2526customUrl%253Dhttp%253A%252F%252Four.umbraco.org%252Fprojects%252Fdeveloper-tools%252F301-url-tracker%2526customControl%253D%252FUmbraco%252FUrlTracker%252FInfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstaller.ascx

It appears to have installed, the only thing I can see so far that is an issue is some double scrollbar action in the dashboard:

![image](https://cloud.githubusercontent.com/assets/1040786/6827094/70b183d0-d2fd-11e4-8305-b3cd9d77a601.png)

Any ideas?

Greg.

**Comment by kipusoep** [comment]
No idea what happened. It looks like it's working though? Double scrollbars is an existing issue: http://issues.umbraco.org/issue/U4-3940

**Comment by gfyans** [comment]
Yea, it is working, just not sure if anything has been missed by me not being able to load the post-install page.

**Comment by gfyans** [comment]
Actually, forgot to mention, I had to add the dashboard item to my dashboard.config manually.

**Comment by kipusoep** [comment]
Yeah that's probably the only thing you missed out on :-)

**Comment by runegronkjaer** [comment]
Hi Guys,

I get the same error on install on a clean Umbraco 7.2.4 and Url tracker 3.6

Also the url rewriting does not work. When I rename a page the entry is correctly appearing in the dashboard, but i get the default "Page not found No umbraco document matches the url '/contact/'." message from Umbraco when loading the old url.

I have no new "notfound" lines in the 404handlers.config. Are there still supposed to be something in that?

/Rune

**Comment by solomonshaffer** [comment]
I also got this error on install and the redirects are not working. Enabled logging and umbracoDebugMode and not getting any writes to the log file. Version 7.2.4

**Comment by Ladefuss** [comment]
Getting the exact same error on a clean 7.2.4

**Comment by Trixxer** [comment]
Also getting this error on a clean 7.2.4.
Tested with a clean 7.2.1 install and there it works just fine.

**Comment by ZNS** [comment]
I was thinking of using this. Does it work with 7.2.4 or not?

**Comment by kipusoep** [comment]
Yay I've reproduced it, working towards a fix atm! :-)

**Comment by kipusoep** [comment]
Yay it's been fixed (issue is due to the query string generated by umbraco is suddenly lower-cased).
It's going to be included in the next release.

**Comment by kipusoep** [comment]
Released this fix with v3.7
