### ISSUE TITLE
Advanced view doesn't work if you don't setup domains in umbraco

### ISSUE THREAD

**Issue by happywalker** [kipusoep/UrlTracker#71]
Hi, 
This is really great umbraco component, and thank you for developing this tool.

There is a small issue for advanced view(version 3.6) if you don't setup domains in umbraco, the code in UrlTracker\UI\UserControls\AdvancedView.ascx should change to something like the following:
from:
ddlRootNode.SelectedValue = UrlTrackerModel.RedirectRootNodeId.ToString();
to:
            if (ddlRootNode.Items.Count > 1)
            {
                ddlRootNode.SelectedValue = UrlTrackerModel.RedirectRootNodeId.ToString();
            }

Hopefully the issue can be fixed in the future releases.

Thank you

**Comment by Elijha** [comment]
"Advanced view" gives me some JS popup errors.. I have 3 root nodes - only one is assigned the domain the others 'extras' and 'settings' are used as data sources and have none .. would the above explain why it is failing?

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by kipusoep** [comment]
No reply, so closing.
