### ISSUE TITLE
When site column is filled out, URL Tracker doesn't work

### ISSUE THREAD

**Issue by lonehorseend** [kipusoep/UrlTracker#73]
I think this might be similar to https://github.com/kipusoep/UrlTracker/issues/65, but I'm not sure.

UrlTracker 3.6 with Umbraco 7.22.

If I try to edit a redirect I created, try and create a new from the regular URL tracker page, or let an automatic one be created, it puts the name of my front page in the site column.  Once that happens, instead of picking up the redirect, it redirects to the site map, which is my Umbraco 404 page. 

When I was running Umbraco 6 and UrlTracker, this wasn't a problem.

**Comment by lonehorseend** [comment]
If I add a domain in Cultures and Host names, the column can be filled out and it works. I get JS errors as mentioned in issue https://github.com/kipusoep/UrlTracker/issues/71, though.

But why should I have to assign a domain name for a single domain based site?

**Comment by meto5000** [comment]
Adding some more info on this issue

I've uploaded some images that explain the problem but here is the gist:

* Create new redirect within Url Tracker
* Link does not redirect
* Editing the link and clicking "Advanced Mode" gives an error (see image)
* Link now appears in the 404 Not Found View
* Creating a redirect from the link inside 404 Not Found makes a redirect link that works properly
* User created links within the Url Tracker View show the Site as "Home"
* Redirect links created from the 404 Not Found View show the Site as a blank field
* In the sql db, the links from the 404 have -1 as RedirectRootNode vs 1055 for User created redirect links

http://imgur.com/a/r7SiP

**Comment by Trixxer** [comment]
I had to go back to version 3.3 to get this working.

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by kipusoep** [comment]
No reply, so closing.
