### ISSUE TITLE
iFrame not filling page - scrolling ensues Umbraco v7.2.2

### ISSUE THREAD

**Issue by nacayoda** [kipusoep/UrlTracker#74]
Is anyone else frustrated with the lack of iframe height for id="urlTrackerIframe" (UrlTracker/UI/UrlTrackerManagerWrapper.ascx)?

The .umb-dashboard-control iframe styles (width:99%; height:99%;) are bad enough, but setting width:100% on the urlTrackIframe ensures a horizontal scrollbar, then omitting a height results in a 150px high slot to view the Url Tracker information.

Can someone add a reference to a css file where we can style this iFrame without recompiling a dll, or alternatively modify this line...

<iframe scrolling="auto" frameborder="0" marginheight="0" marginwidth="0" id="urlTrackerIframe" seamless="seamless" name="urltracker" src="<%= UrlTrackerResources.UrlTrackerManagerUrl %>" style="width: 100%;"></iframe>

to

<iframe scrolling="auto" frameborder="0" marginheight="0" marginwidth="0" id="urlTrackerIframe" seamless="seamless" name="urltracker" src="<%= UrlTrackerResources.UrlTrackerManagerUrl %>" style="width: 90%; height:1200px;"></iframe>

Or... educate me about why this might be occurring to just me ;)
I installed v3 via NuGet. Re-compiling this myself and redeploying is outside my knowledge base I'm afraid.

Cheers,
NY

**Comment by kipusoep** [comment]
It's not up to me unfortunately: http://issues.umbraco.org/issue/U4-3940

**Comment by nacayoda** [comment]
Thanks for the link. I see I'm not going crazy.
Can you hack it in for the time being as per my fork?
Inspecting the iframe every time I use the interface to insert a height in the Browser console is maddening.
adding a 
<link> or style @import to a <root>/tracker.css or something would also allow me to style the iframe in question without having to compile code.

multiple scrollbars are not elegant, but at least the information will be more accessible than currently.

**Comment by nacayoda** [comment]
![capture](https://cloud.githubusercontent.com/assets/6855957/7040763/d165a832-de15-11e4-8918-261ecee240e1.PNG)
Here is a picture of the limited visible area.
