### ISSUE TITLE
Not allowed root "/" in old url

### ISSUE THREAD

**Issue by yonatancohen** [kipusoep/UrlTracker#79]
Hi, I want to define the next rule :
![capture](https://cloud.githubusercontent.com/assets/10291980/7750850/39cc4bb6-ffdf-11e4-8d2d-b57c11a2ab32.JPG)

However i get an error that the rule is invalid... Can't i use the "/" in old url?
when I look in the DB it's save as "NULL", but if i change the value to "/" - all works fine..

Anyway for quick fixing?

**Comment by kipusoep** [comment]
The reason is because the smallest URL is being stored; this means without leading and trailing slash. That's why NULL is stored in the database.

**Comment by yonatancohen** [comment]
Anyway to override that option?

I have the following urls :
*    http://www.test.com?Id=John   -> and i need to redirect to
http://www.test.com/John
*    http://www.test.com?Id=Larry   -> and i need to redirect to
http://www.test.com/Larry

Can i do that using the "Url Tracker"?

Thanks !!!!!


‫בתאריך יום ה׳, 21 במאי 2015 ב-17:34 מאת ‪Stefan Kip‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by kipusoep** [comment]
Not via the UI, if it works via SQL you're lucky :-)

**Comment by yonatancohen** [comment]
Ok, so i'll download the code and try to add it myself.

Thanks,

**Comment by kipusoep** [comment]
I'll try to fix this soonish :-)

**Comment by yonatancohen** [comment]
I will really appreciate it!!

**Comment by yonatancohen** [comment]
Hi, I wonder if you go into it?

Thanks,

‫בתאריך יום ו׳, 22 במאי 2015 ב-17:29 מאת ‪Yoni Cohen‬‏ <‪
yoni.n.cohen@gmail.com‬‏>:‬

> I will really appreciate it!!

**Comment by kipusoep** [comment]
Fixed in 2fad9b7baddff5200fc46defeb5c76e3541b8cb3, not released yet though.

**Comment by yonatancohen** [comment]
Ok.. So first thanks a lot !
Second, when do you think you will release it?

**Comment by kipusoep** [comment]
When there's a bit more to release. You can download the solution and create a build for yourself though, no sweat.

**Comment by yonatancohen** [comment]
Hi, now it's allow to add "/" at root - but doesn't do the redirect itself.



‫בתאריך יום ג׳, 26 במאי 2015 ב-23:34 מאת ‪Stefan Kip‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by kipusoep** [comment]
It works for me though, altough I tried by setting no root node (root node set to the first option '/').
Does it work if you select no root node (first option)?

**Comment by yonatancohen** [comment]
Both doesn't seem to work,

I set the root (in combo) to "/",
Enter some query "Id=123",
and the redirect path to "http://www.google.com"

‫בתאריך יום ה׳, 28 במאי 2015 ב-15:03 מאת ‪Stefan Kip‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by kipusoep** [comment]
Then I'm not sure what's going on to be honest...
