### ISSUE TITLE
Which Url Tracker version to use with U 6.2.4?

### ISSUE THREAD

**Issue by MichaelSteenC** [kipusoep/UrlTracker#80]
Hi

Which version of Url Tracker is the correct version, when I'm using Umbraco 6.2.4? 

Your readme.md says "Version 3 is the current version and supports umbraco versions 6.1, 7.0, 7.1 and up if possible." so the 6.2 is not mentioned. 

I just want to be sure about the version before I try to install one of the packages.

Thank you for helping.

**Comment by kipusoep** [comment]
vLatest
