### ISSUE TITLE
Mass 301 upload through CSV, orther format?

### ISSUE THREAD

**Issue by driver105** [kipusoep/UrlTracker#82]
I need to set up a large batch of 301s for the first time.  Is it possible to upload a CSV or other file format vs. having to go in an manually input these things one by one?  I didn't see any mention of this, but assume I can.  And if so, in what format and columns should these be created ... as an example, would I take this entire string and break it into columns, or do I only need parts of this in columns? 
RewriteRule ^/ product\.php\? prod-id \= 59 $ http:// http://www.gerstelus.com/product-categories/ [R=301,L]

Thanks in advance for your help!

**Comment by kipusoep** [comment]
This is completely up to you. The easiest way is to import the CSV to SQL with SQL Server Management Studio.
