### ISSUE TITLE
Clicking Preview in Umbraco causes exception

### ISSUE THREAD

**Issue by garpunkal** [kipusoep/UrlTracker#85]
[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.UmbracoContext.get_UmbracoUser() +10
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.<get_GetXmlDelegate>b__3(UmbracoContext context, Boolean preview) +91
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetXml(UmbracoContext umbracoContext, Boolean preview) +150
   umbraco.presentation.UmbracoContext.GetXml() +189
   umbraco.library.GetXmlNodeById(String id) +36
   umbraco.NodeFactory.Node..ctor(Int32 NodeId) +492
   InfoCaster.Umbraco.UrlTracker.Models.UrlTrackerDomain.get_Node() in d:\kipusoep\Documents\GitHub\UrlTracker\Models\UrlTrackerDomain.cs:16
   InfoCaster.Umbraco.UrlTracker.Models.UrlTrackerDomain.get_UrlWithDomain() in d:\kipusoep\Documents\GitHub\UrlTracker\Models\UrlTrackerDomain.cs:21
   InfoCaster.Umbraco.UrlTracker.Modules.<>c__DisplayClassc.<UrlTrackerDo>b__2(UrlTrackerDomain x) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:149
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +168
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:149
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +91
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164

Any help?

**Comment by kipusoep** [comment]
What version

**Comment by garpunkal** [comment]
3.8. Trying to preview a content item without a template

**Comment by garpunkal** [comment]
If I disable UrlTracker, it resolves to a 404.

**Comment by kipusoep** [comment]
This should work again with v3.9 and Umbraco 7.3.2.
