### ISSUE TITLE
Manual entries in the DB

### ISSUE THREAD

**Issue by danimalx** [kipusoep/UrlTracker#88]
Hi

I am migrating a site and need to pull all the manual entries out of the DB to copy to my new site. How can I identify these?

Thanks

Dan

**Comment by kipusoep** [comment]
This is the logic behing auto/404/manual entries: https://github.com/kipusoep/UrlTracker/blob/master/Models/UrlTrackerModel.cs#L199

**Comment by danimalx** [comment]
Thanks for that. I also had to add "Node removed" and got this SQL to work:

select * 
FROM [dbo].[icUrlTracker]
where ((notes not like 'A parent%'
and notes not like 'An ancestor%'
and notes not like 'This page%'
and notes not like 'This document%'
and notes not like '%was moved'
and notes not like '%was renamed'
and notes not like '%node removed%'
and notes not like '%''s property ''umbracoUrlName'' changed') or notes is null)
and Is404 != 1
