### ISSUE TITLE
Columns not correct width

### ISSUE THREAD

**Issue by Myster** [kipusoep/UrlTracker#89]
Hi, The url tracker table usually looks pretty wacky, It looks like the column widths are not set correctly for the scenario when urls are long, this is much worse if the 'site' is longer than 'home'

![Image of layout issue](https://our.umbraco.org/media/upload/d066b01a-e902-47ce-b9ac-ddbecfb64662/301-squish.JPG)

I think setting a minimum width on each column would help
From [forum post](https://our.umbraco.org/projects/developer-tools/301-url-tracker/version-2/69931-columns-not-correct-width#comment-225984)

**Comment by kipusoep** [comment]
Thanks for reporting. Have you had any chance to test this yourself? A pull request would be great and really suitable for such a change.

**Comment by JBoye** [comment]
@Myster What version are you using? This should be fixed in 3.5: https://github.com/kipusoep/UrlTracker/issues/27

**Comment by Myster** [comment]
according to the DLL properties it's 3.0.1.0, guess I should try an upgrade :-)

**Comment by kipusoep** [comment]
Please do :-) Always try the latest version first before reporting bugs, as they might be solved already.

**Comment by Myster** [comment]
Yep, that's the trick.
Thanks for all your work on this software, it's in all our solutions, and it's a really useful piece of the puzzle.

**Comment by kipusoep** [comment]
Great! Thanks for the kind words :-)
