### ISSUE TITLE
410 Gone - Optional?

### ISSUE THREAD

**Issue by valeriegibson** [kipusoep/UrlTracker#92]
Hello,

Is there a way to stop the url tracker adding entries as 410 gone? We would just like it to show a 404 in these cases, as the 410 response just shows a white page. There doesn't seem to be a way to handle this in Umbraco to show a page similar to a 404 template.

IIS also doesn't seem to let us serve up the page.

**Comment by kipusoep** [comment]
Well it's possible to serve your own page, because I've done it :-)  
Anyway, it's currently not possible to stop the 410 entries.

**Comment by valeriegibson** [comment]
How did you do it?

**Comment by kipusoep** [comment]
I wrote my own customErrors section for the web.config with custom code to handle displaying a custom page, because I wasn't happy with the way ASP.NET/Umbraco does it OOTB.

**Comment by tvanro** [comment]
Would it be possible to configure the 410 to become a 404 instead? When we unpublish a node this should be entered as a 404 for our project....

**Comment by jessetinell** [comment]
I don't like the way UrlTracker handles 410 entries either. I would like to show the 404 instead (like Umbraco does).

+1 for a setting to disable this.

How should I redirect 410s to 404 in the best way? I really don't want to add some own custom hacks. I've tried adding custom httpErrors to my web.config. It works OK but I end up with more problems that also must be "hack"-solved.

**Comment by mike-w-kelly** [comment]
+1 for a setting to turn this off, my users just want the 404 behaviour. Thanks

**Comment by jattwood** [comment]
I would also like to upvote this. Since umbraco gives us no easy way to specify any errors other than 500 and 404, adding boolean in settings: "interpret410As404 = true" would be a great addition to URL tracker.

Thanks!

**Comment by CasperTDK** [comment]
I would really like to show the 404 page for 410 but keep the response code! that would be ideel for me.
+1

**Comment by daniel-chenery** [comment]
Hi guys,

This is a highly requested feature, and I'll get to it when I can.
Since there are many ideas put forward here, are you happy with an event going forward?

You could then customise the 410 (or any redirect) to your hearts content
Something like the following

```c#
InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.PreUrlTracker += UrlTrackerModule_PreUrlTracker;

private void UrlTrackerModule_PreUrlTracker(object sender, HttpResponse e)
{
	if (e.StatusCode == 410)
	{
		e.StatusCode = 404;
	}
}
```

**Comment by daniel-chenery** [comment]
See [here](https://github.com/kipusoep/UrlTracker#events)
