### ISSUE TITLE
Bulk Import Redirects Feature

### ISSUE THREAD

**Issue by Nicholas-Westby** [kipusoep/UrlTracker#95]
This tool is really useful for converting 404's into redirects. However, it would be even more valuable if there were some ability to import redirects (e.g., from a CSV).

Working for an agency, we frequently rebuild websites and create a new URL structure. Before the new site goes live, we like to redirect URL's from the old path to the new one. We typically do this in the web.config, as manually entering them with this tool is too time consuming when we have hundreds or thousands of initial redirects to populate. The downside of that is that we can't then edit those redirects with a nice GUI in Umbraco like we can with this tool.

**Comment by kipusoep** [comment]
Hi, it's too easy to import records in the UrlTracker SQL table with SQL Server Management Studio, so I'm not going to build this, sorry.

**Comment by Nicholas-Westby** [comment]
Fair enough, and thanks for the quick response.

One nifty thing that a bulk import could do that would be very hard to do with SSMS would be to automatically associate the destination URL's with nodes rather than paths (i.e., so if somebody renames that node, the redirect gets updated automatically, which I assume 301 URL Tracker already does).

**Comment by kipusoep** [comment]
Yes you're right, but if you've got many redirects like that it'll be worth it to write a simple script to do this yourself I guess?

**Comment by Nicholas-Westby** [comment]
The quick way is to use RegEx Buddy to convert the redirects into the format expected by the web.config, which is what I usually do. It doesn't have all the awesomeness of 301 URL Tracker, however.

Would you be open to a pull request for this feature (i.e., a bulk import that infers node based on destination URL)?

**Comment by kipusoep** [comment]
Sure! I <3 PR's, though all support will be in your hands.
I've had a major PR in the past, accepted it and then the  Bug Reports started coming. The person who did the PR was unreachable and I had to revert everything, which was hell!
So I don't want that to happen again.

**Comment by kipusoep** [comment]
Btw, another option is to build it as a side-project, as an add-on for the Url Tracker itself?

**Comment by Nicholas-Westby** [comment]
I suppose I could integrate it as a new sample Rhythm Data Processor (not really a true Umbraco plugin yet): https://github.com/rhythmagency/rhythm.umbraco7.data-processor

Since it's just basically just some SQL inserts, shouldn't be too far out of the scope of what I built that project to do (namely, get some data and perform some operation on it, such as the case here with a bulk import).

Just seems very tied to what 301 URL Tracker does, and so it would make a lot of sense for it to be part of the tool itself. Could go either way, really.

Does 301 URL Tracker have some sort of add-on model already?

**Comment by kipusoep** [comment]
"Does 301 URL Tracker have some sort of add-on model already?"

Nope ;-)
